name: Dind (Docker-in-Docker)
description: Start and cleanup a dind container
author: https://github.com/ray-project
requirements: ["docker"]
configuration:
  properties:
    network-name:
      type: string
    certs-volume-name:
      type: string
    additional-volume-mount:
      type: string
  additionalProperties: false