#! /usr/bin/env bash

set -eux

echo "--- :docker: setting up docker-in-docker"

if docker ps -q --filter="name=dind-daemon" | grep -q .; then
    echo "--- :docker: dind-daemon already exists!"
else
    echo "--- :docker: creating dind-daemon"
    docker network create "$BUILDKITE_PLUGIN_DIND_NETWORK_NAME" || true
    docker rm -f -v dind-daemon || true

    docker run --privileged --name dind-daemon -d --rm \
        --network "$BUILDKITE_PLUGIN_DIND_NETWORK_NAME" --network-alias docker \
        -e DOCKER_TLS_CERTDIR=/certs \
        -v docker-certs-ca:/certs/ca \
        -v "$BUILDKITE_PLUGIN_DIND_CERTS_VOLUME_NAME":/certs/client \
        -v "$BUILDKITE_PLUGIN_DIND_ADDITIONAL_VOLUME_MOUNT" \
        docker:dind
fi
